modLoader="javafml"
loaderVersion="[47,)"
license="AGPL-3.0-or-later"
issueTrackerURL="https://github.com/gerald/dynamic_trees_dimension_compat/issues"

[[mods]]
modId="dynamic_trees_dimension_compat"
version="${file.jarVersion}"
displayName="Better Content Dynamic Trees: Dimensions"
authors="gerald"
description='''Dynamic Trees compatibility for pack dimension forest trees without published addons.'''

[[dependencies.dynamic_trees_dimension_compat]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.4.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="blue_skies"
    mandatory=false
    versionRange="[1.3.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="undergarden"
    mandatory=false
    versionRange="[0.8.14,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="the_finley_dimension_remastered"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="callfromthedepth_"
    mandatory=false
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="dynamictreesplus"
    mandatory=false
    versionRange="[1.2.0,)"
    ordering="AFTER"
    side="BOTH"
