modLoader="javafml"
loaderVersion="[47,)"
license="AGPL-3.0-or-later"
issueTrackerURL="https://github.com/better-content/dynamic-trees-dimension-compat/issues"

[[mods]]
modId="dynamic_trees_dimension_compat"
version="${file.jarVersion}"
displayName="Better Content Dynamic Trees: Dimensions"
displayURL="https://github.com/better-content/dynamic-trees-dimension-compat"
authors="gerald"
description='''Dynamic Trees compatibility for The Undergarden's grongle, smogstem, and wigglewood forests.'''

[[dependencies.dynamic_trees_dimension_compat]]
    modId="forge"
    mandatory=true
    versionRange="[47.4.13,48)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="dynamictrees"
    mandatory=true
    versionRange="[1.20.1-1.4.10,1.20.1-1.5.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.dynamic_trees_dimension_compat]]
    modId="undergarden"
    mandatory=true
    versionRange="[0.8.14,)"
    ordering="AFTER"
    side="BOTH"
